import Mathlib

/--
Degree-2 cohomology of CP^∞ is modeled by ℤ.
Degree-2 cohomology of RP^∞ is modeled by ℤ/2ℤ.
The induced map q* is the canonical projection.
-/
def qStarDegreeTwo : ℤ →+ ZMod 2 :=
  Int.castAddHom (ZMod 2)

/--
q* : H²(CP^∞;ℤ) → H²(RP^∞;ℤ)
is surjective.
-/
theorem qStar_degree_two_surjective :
    Function.Surjective qStarDegreeTwo := by
  intro x
  obtain ⟨z, hz⟩ := ZMod.intCast_surjective x
  exact ⟨z, hz⟩

/--
The degree-2 generator maps to the nonzero generator mod 2.
-/
theorem qStar_degree_two_generator :
    qStarDegreeTwo 1 = (1 : ZMod 2) := by
  rfl

theorem qStar_degree_two_nonzero :
    qStarDegreeTwo ≠ 0 := by
  intro h
  have h1 : qStarDegreeTwo 1 = 0 := by
    rw [h]
    rfl
  norm_num [qStarDegreeTwo] at h1

/--
A simple algebraic model for even-degree cohomology.

In degree 2k:
* CP^∞ contributes ℤ, generated by c^k;
* RP^∞ contributes ℤ/2ℤ, generated by a^k;
* q* reduces the coefficient modulo 2.
-/
def qStarEven (_k : ℕ) : ℤ →+ ZMod 2 :=
  Int.castAddHom (ZMod 2)

theorem qStar_even_surjective
    (k : ℕ) :
    Function.Surjective (qStarEven k) := by
  intro x
  obtain ⟨z, hz⟩ := ZMod.intCast_surjective x
  exact ⟨z, hz⟩

theorem qStar_even_generator
    (k : ℕ) :
    qStarEven k 1 = (1 : ZMod 2) := by
  rfl

/--
Summary: the induced map is surjective in every positive even degree.
-/
theorem qStar_surjective_in_even_dimensions :
    ∀ k : ℕ,
      Function.Surjective (qStarEven k) := by
  intro k
  exact qStar_even_surjective k
