import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option grind.warning false

/-!
# A group of order 12 has a normal Sylow subgroup

The proof is the classical counting argument (an application of **Sylow's theorems**):
the number `n₃` of Sylow `3`-subgroups divides `4` and is `≡ 1 [MOD 3]`, hence `n₃ = 1`
or `n₃ = 4`.  If `n₃ = 1` the Sylow `3`-subgroup is normal.  If `n₃ = 4`, the four Sylow
`3`-subgroups pairwise intersect trivially, so they account for `4 * 2 = 8` elements of
order `3`; the remaining `4` elements must therefore constitute the unique Sylow
`2`-subgroup, which is consequently normal.

The theorem that answers the accompanying multiple-choice question is therefore
**(a) Sylow's theorem**.
-/

namespace Order12

open Finset

variable {G : Type*} [Group G] [Fintype G]

local instance factThree : Fact (Nat.Prime 3) := ⟨by norm_num⟩
local instance factTwo : Fact (Nat.Prime 2) := ⟨by norm_num⟩

lemma factorization_twelve_three : (12 : ℕ).factorization 3 = 1 := by
  have h : (12 : ℕ).factorization = Nat.factorization (2 ^ 2 * 3 ^ 1) := by norm_num
  rw [h, Nat.factorization_mul (by norm_num) (by norm_num),
    Nat.Prime.factorization_pow Nat.prime_two, Nat.Prime.factorization_pow Nat.prime_three]
  simp

lemma factorization_twelve_two : (12 : ℕ).factorization 2 = 2 := by
  have h : (12 : ℕ).factorization = Nat.factorization (2 ^ 2 * 3 ^ 1) := by norm_num
  rw [h, Nat.factorization_mul (by norm_num) (by norm_num),
    Nat.Prime.factorization_pow Nat.prime_two, Nat.Prime.factorization_pow Nat.prime_three]
  simp

/-- A Sylow `3`-subgroup of a group of order `12` has order `3`. -/
lemma card_sylow_three (hG : Fintype.card G = 12) (P : Sylow 3 G) :
    Nat.card (P : Subgroup G) = 3 := by
  have hcard : Nat.card G = 12 := by rw [Nat.card_eq_fintype_card, hG]
  rw [P.card_eq_multiplicity, hcard, factorization_twelve_three, pow_one]

/-- A Sylow `2`-subgroup of a group of order `12` has order `4`. -/
lemma card_sylow_two (hG : Fintype.card G = 12) (Q : Sylow 2 G) :
    Nat.card (Q : Subgroup G) = 4 := by
  have hcard : Nat.card G = 12 := by rw [Nat.card_eq_fintype_card, hG]
  rw [Q.card_eq_multiplicity, hcard, factorization_twelve_two]
  norm_num

/-- The number of Sylow `3`-subgroups of a group of order `12` is `1` or `4`. -/
lemma card_sylow_three_cases (hG : Fintype.card G = 12) :
    Nat.card (Sylow 3 G) = 1 ∨ Nat.card (Sylow 3 G) = 4 := by
  obtain ⟨P⟩ : Nonempty (Sylow 3 G) := inferInstance
  have hcard : Nat.card G = 12 := by rw [Nat.card_eq_fintype_card, hG]
  have hindex : (P : Subgroup G).index = 4 := by
    have h := Subgroup.card_mul_index (P : Subgroup G)
    rw [card_sylow_three hG P, hcard] at h
    omega
  have hdvd : Nat.card (Sylow 3 G) ∣ 4 := hindex ▸ P.card_dvd_index
  have hmod : Nat.card (Sylow 3 G) % 3 = 1 % 3 := card_sylow_modEq_one 3 G
  have hle : Nat.card (Sylow 3 G) ≤ 4 := Nat.le_of_dvd (by norm_num) hdvd
  interval_cases h : Nat.card (Sylow 3 G) <;> revert hdvd <;> omega

/-- In a group of order `12`, the subgroup generated by an element of order `3`
is a Sylow `3`-subgroup. -/
lemma zpowers_isSylow (hG : Fintype.card G = 12) {g : G} (hg : orderOf g = 3) :
    Nat.card (Subgroup.zpowers g) = 3 ^ ((Nat.card G).factorization 3) := by
  have hcard : Nat.card G = 12 := by rw [Nat.card_eq_fintype_card, hG]
  rw [Nat.card_zpowers, hg, hcard, factorization_twelve_three, pow_one]

/-- An element of order `3` lying in a Sylow `3`-subgroup `P` generates `P`. -/
lemma eq_zpowers_of_mem (hG : Fintype.card G = 12) (P : Sylow 3 G) {g : G}
    (hg : orderOf g = 3) (hmem : g ∈ (P : Subgroup G)) :
    (P : Subgroup G) = Subgroup.zpowers g := by
  refine (Subgroup.eq_of_le_of_card_ge ?_ ?_).symm
  · rw [Subgroup.zpowers_le]; exact hmem
  · rw [Nat.card_zpowers, hg, card_sylow_three hG P]

/-- Inside a Sylow `3`-subgroup of a group of order `12`, exactly two elements have order `3`. -/
lemma card_orderThree_in_sylow (hG : Fintype.card G = 12) (P : Sylow 3 G) :
    (Finset.univ.filter (fun g : G => g ∈ (P : Subgroup G) ∧ orderOf g = 3)).card = 2 := by
  classical
  have hP3 : Nat.card (P : Subgroup G) = 3 := card_sylow_three hG P
  have hfil : (Finset.univ.filter (fun g : G => g ∈ (P : Subgroup G))).card = 3 := by
    rw [← Fintype.card_subtype (fun g : G => g ∈ (P : Subgroup G)), ← Nat.card_eq_fintype_card]
    exact hP3
  have hone : (1 : G) ∈ Finset.univ.filter (fun g : G => g ∈ (P : Subgroup G)) := by
    simp
  have hset : (Finset.univ.filter (fun g : G => g ∈ (P : Subgroup G) ∧ orderOf g = 3))
      = (Finset.univ.filter (fun g : G => g ∈ (P : Subgroup G))).erase 1 := by
    ext g
    simp only [Finset.mem_filter, Finset.mem_univ, true_and, Finset.mem_erase]
    constructor
    · rintro ⟨hgP, ho⟩
      refine ⟨?_, hgP⟩
      rintro rfl
      simp at ho
    · rintro ⟨hne, hgP⟩
      refine ⟨hgP, ?_⟩
      have hdvd : orderOf (⟨g, hgP⟩ : (P : Subgroup G)) ∣ Nat.card (P : Subgroup G) := by
        rw [Nat.card_eq_fintype_card]; exact orderOf_dvd_card
      rw [← Subgroup.orderOf_coe, hP3] at hdvd
      have h3 : Nat.Prime 3 := by norm_num
      rcases (Nat.Prime.eq_one_or_self_of_dvd h3 _ hdvd) with h | h
      · exact absurd (orderOf_eq_one_iff.mp h) hne
      · exact h
  rw [hset, Finset.card_erase_of_mem hone, hfil]

/-- The number of elements of order `3` is twice the number of Sylow `3`-subgroups. -/
lemma card_orderThree (hG : Fintype.card G = 12) :
    (Finset.univ.filter (fun g : G => orderOf g = 3)).card = 2 * Nat.card (Sylow 3 G) := by
  classical
  haveI : Fintype (Sylow 3 G) := Fintype.ofFinite _
  have hT : (Finset.univ.filter (fun g : G => orderOf g = 3))
      = Finset.univ.biUnion (fun P : Sylow 3 G =>
          Finset.univ.filter (fun g : G => g ∈ (P : Subgroup G) ∧ orderOf g = 3)) := by
    ext g
    rw [Finset.mem_biUnion]
    simp only [Finset.mem_filter, Finset.mem_univ, true_and]
    constructor
    · intro hg
      refine ⟨Sylow.ofCard (Subgroup.zpowers g) (zpowers_isSylow hG hg), ⟨?_, hg⟩⟩
      have : ((Sylow.ofCard (Subgroup.zpowers g) (zpowers_isSylow hG hg) : Sylow 3 G) :
          Subgroup G) = Subgroup.zpowers g := Sylow.coe_ofCard _ _
      rw [this]
      exact Subgroup.mem_zpowers g
    · rintro ⟨P, -, hg⟩
      exact hg
  have hdisj : (↑(Finset.univ : Finset (Sylow 3 G)) : Set (Sylow 3 G)).PairwiseDisjoint
      (fun P : Sylow 3 G => Finset.univ.filter (fun g : G => g ∈ (P : Subgroup G)
        ∧ orderOf g = 3)) := by
    intro P _ Q _ hPQ
    simp only [Function.onFun]
    rw [Finset.disjoint_left]
    rintro a ha hb
    simp only [Finset.mem_filter, Finset.mem_univ, true_and] at ha hb
    exact hPQ (Sylow.ext (by
      rw [eq_zpowers_of_mem hG P ha.2 ha.1, eq_zpowers_of_mem hG Q hb.2 hb.1]))
  rw [hT, Finset.card_biUnion hdisj]
  rw [Finset.sum_congr rfl (fun P _ => card_orderThree_in_sylow hG P)]
  rw [Finset.sum_const, smul_eq_mul, Nat.card_eq_fintype_card, Finset.card_univ]
  ring

/-- If there are four Sylow `3`-subgroups, then a Sylow `2`-subgroup consists exactly of the
elements whose order is not `3`. -/
lemma sylow_two_eq (hG : Fintype.card G = 12) (h4 : Nat.card (Sylow 3 G) = 4) (Q : Sylow 2 G) :
    Finset.univ.filter (fun g : G => g ∈ (Q : Subgroup G))
      = Finset.univ.filter (fun g : G => ¬ orderOf g = 3) := by
  classical
  have h8 : (Finset.univ.filter (fun g : G => orderOf g = 3)).card = 8 := by
    rw [card_orderThree hG, h4]
  have hsplit := Finset.card_filter_add_card_filter_not
    (s := (Finset.univ : Finset G)) (p := fun g : G => orderOf g = 3)
  rw [Finset.card_univ, hG, h8] at hsplit
  have hQ4 : (Finset.univ.filter (fun g : G => g ∈ (Q : Subgroup G))).card = 4 := by
    rw [← Fintype.card_subtype (fun g : G => g ∈ (Q : Subgroup G)), ← Nat.card_eq_fintype_card]
    exact card_sylow_two hG Q
  have hsub : Finset.univ.filter (fun g : G => g ∈ (Q : Subgroup G))
      ⊆ Finset.univ.filter (fun g : G => ¬ orderOf g = 3) := by
    intro g hg
    simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hg ⊢
    have hdvd : orderOf (⟨g, hg⟩ : (Q : Subgroup G)) ∣ Nat.card (Q : Subgroup G) := by
      rw [Nat.card_eq_fintype_card]; exact orderOf_dvd_card
    rw [← Subgroup.orderOf_coe, card_sylow_two hG Q] at hdvd
    intro h3
    rw [h3] at hdvd
    omega
  exact Finset.eq_of_subset_of_card_le hsub (by omega)

/-- **Main theorem**: a group of order `12` has a normal Sylow subgroup. -/
theorem Q22 (G : Type*) [Group G] [Fintype G] (hG : Fintype.card G = 12) :
    ∃ p : ℕ, Nat.Prime p ∧ ∃ P : Sylow p G, (P : Subgroup G).Normal := by
  classical
  rcases card_sylow_three_cases hG with h1 | h4
  · obtain ⟨P⟩ : Nonempty (Sylow 3 G) := inferInstance
    haveI : Subsingleton (Sylow 3 G) := (Nat.card_eq_one_iff_unique.mp h1).1
    exact ⟨3, by norm_num, P, Sylow.normal_of_subsingleton P⟩
  · obtain ⟨Q⟩ : Nonempty (Sylow 2 G) := inferInstance
    haveI : Subsingleton (Sylow 2 G) := by
      refine ⟨fun Q₁ Q₂ => Sylow.ext (SetLike.ext fun g => ?_)⟩
      have h1 := sylow_two_eq hG h4 Q₁
      have h2 := sylow_two_eq hG h4 Q₂
      have := h1.trans h2.symm
      have hg := Finset.ext_iff.mp this g
      simpa using hg
    exact ⟨2, by norm_num, Q, Sylow.normal_of_subsingleton Q⟩

end Order12
