import Mathlib

/-- If `a` has order `n` in a group and `k : ℕ`, then the subgroup generated by `a ^ k`
equals the subgroup generated by `a ^ gcd n k`.  The proof uses Bézout's identity:
`gcd n k = n * u + k * v` for suitable integers `u, v`, so `a ^ gcd n k = (a ^ k) ^ v`. -/
theorem Gallian_2
    {G : Type*} [Group G] (a : G) (n k : ℕ)
    (hord : orderOf a = n) :
    Subgroup.closure ({a ^ k} : Set G)
      = Subgroup.closure ({a ^ Nat.gcd n k} : Set G) := by
  have han : a ^ n = 1 := by
    rw [← hord]; exact pow_orderOf_eq_one a
  apply le_antisymm
  · rw [Subgroup.closure_le]
    rintro x hx
    simp only [Set.mem_singleton_iff] at hx
    subst hx
    obtain ⟨c, hc⟩ := Nat.gcd_dvd_right n k
    have hk : a ^ k = (a ^ Nat.gcd n k) ^ c := by rw [← pow_mul, ← hc]
    rw [hk]
    exact Subgroup.pow_mem _ (Subgroup.subset_closure (Set.mem_singleton _)) c
  · rw [Subgroup.closure_le]
    rintro x hx
    simp only [Set.mem_singleton_iff] at hx
    subst hx
    have hb : (Nat.gcd n k : ℤ) = n * Nat.gcdA n k + k * Nat.gcdB n k :=
      Nat.gcd_eq_gcd_ab n k
    have : (a : G) ^ (Nat.gcd n k : ℤ) = (a ^ k) ^ (Nat.gcdB n k) := by
      rw [hb, zpow_add, zpow_mul, zpow_mul]
      simp [zpow_natCast, han]
    have h2 : (a : G) ^ (Nat.gcd n k) = (a ^ k) ^ (Nat.gcdB n k) := by
      rw [← this, zpow_natCast]
    rw [h2]
    exact Subgroup.zpow_mem _ (Subgroup.subset_closure (Set.mem_singleton _)) _
