import Mathlib

/-!
# A field of order `2 ^ n` has characteristic `2`

Let `F` be a finite field with `Fintype.card F = 2 ^ n`. Its characteristic is a
prime `p`, and by Lagrange's theorem (applied to the additive subgroup generated by
`1`, whose order is `p`) we get `p ∣ card F = 2 ^ n`. Since `p` is prime this forces
`p = 2`.
-/

/-- The characteristic of a finite field divides its cardinality.
This is Lagrange's theorem for the cyclic additive subgroup generated by `1`,
which has order `char F`. -/
theorem char_dvd_card_of_finite_field (F : Type*) [Field F] [Fintype F]
    (p : ℕ) [hp : CharP F p] : p ∣ Fintype.card F := by
  obtain ⟨m, _, hm⟩ := FiniteField.card F p
  exact hm ▸ dvd_pow_self p m.ne_zero

/-- **A field of order `2 ^ n` has characteristic `2`.** -/
theorem Gallian_18
    (F : Type*) [Field F] [Fintype F]
    (n : ℕ) (hcard : Fintype.card F = 2 ^ n) :
    CharP F 2 := by
  -- Sea `p` la característica de `F` (que es prima).
  obtain ⟨p, hp⟩ := CharP.exists F
  have : CharP F p := hp
  have hpp : Fact p.Prime := ⟨CharP.char_is_prime F p⟩
  -- Por Lagrange, `p ∣ card F = 2 ^ n`, y como `p` es primo, fuerza `p = 2`.
  have hdvd : p ∣ 2 ^ n := hcard ▸ char_dvd_card_of_finite_field F p
  have hp_eq : p = 2 := (Nat.prime_dvd_prime_iff_eq hpp.out Nat.prime_two).mp
    (hpp.out.dvd_of_dvd_pow hdvd)
  exact hp_eq ▸ hp
