import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

open MeasureTheory ProbabilityTheory MeasurableSpace in
/-- The σ-algebra generated by the indicator function of `A` is contained in the
σ-algebra generated by `A`: every preimage of a set of reals under `1_A` is one of
`∅`, `A`, `Aᶜ`, `univ`. -/
theorem comap_indicator_le_generateFrom {Ω : Type*} [MeasurableSpace Ω] (A : Set Ω) :
    MeasurableSpace.comap (A.indicator (fun _ ↦ (1 : ℝ))) inferInstance
      ≤ MeasurableSpace.generateFrom {A} := by
  rintro t ⟨s, -, rfl⟩
  have hAmem : MeasurableSet[MeasurableSpace.generateFrom {A}] A :=
    measurableSet_generateFrom rfl
  by_cases h1 : (1 : ℝ) ∈ s <;> by_cases h0 : (0 : ℝ) ∈ s
  · have h : (A.indicator (fun _ ↦ (1 : ℝ))) ⁻¹' s = Set.univ := by
      ext ω; by_cases hω : ω ∈ A <;> simp [hω, h1, h0]
    rw [h]; exact MeasurableSet.univ
  · have h : (A.indicator (fun _ ↦ (1 : ℝ))) ⁻¹' s = A := by
      ext ω; by_cases hω : ω ∈ A <;> simp [hω, h1, h0]
    rw [h]; exact hAmem
  · have h : (A.indicator (fun _ ↦ (1 : ℝ))) ⁻¹' s = Aᶜ := by
      ext ω; by_cases hω : ω ∈ A <;> simp [hω, h1, h0]
    rw [h]; exact hAmem.compl
  · have h : (A.indicator (fun _ ↦ (1 : ℝ))) ⁻¹' s = ∅ := by
      ext ω; by_cases hω : ω ∈ A <;> simp [hω, h1, h0]
    rw [h]; exact @MeasurableSet.empty Ω (MeasurableSpace.generateFrom {A})

/-- The indicator variables `I_A` and `I_B` are independent random variables iff the
events `A` and `B` are independent. -/
theorem problem_12
  {Ω : Type*} [MeasurableSpace Ω]
  (μ : MeasureTheory.Measure Ω) [MeasureTheory.IsProbabilityMeasure μ]
  (A B : Set Ω) (hA : MeasurableSet A) (hB : MeasurableSet B) :
  ProbabilityTheory.IndepFun
      (A.indicator (fun _ ↦ (1 : ℝ)))
      (B.indicator (fun _ ↦ (1 : ℝ)))
      μ
    ↔ ProbabilityTheory.IndepSet A B μ := by
  constructor
  · intro h
    have key := h.measure_inter_preimage_eq_mul (s := {1}) (t := {1})
      (measurableSet_singleton 1) (measurableSet_singleton 1)
    have hA' : (A.indicator (fun _ ↦ (1 : ℝ))) ⁻¹' {1} = A := by ext ω; simp
    have hB' : (B.indicator (fun _ ↦ (1 : ℝ))) ⁻¹' {1} = B := by ext ω; simp
    rw [hA', hB'] at key
    exact (ProbabilityTheory.indepSet_iff_measure_inter_eq_mul hA hB μ).2 key
  · intro h t1 t2 ht1 ht2
    exact h t1 t2 (comap_indicator_le_generateFrom A _ ht1)
      (comap_indicator_le_generateFrom B _ ht2)

